# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
defaults: &defaults
  docker:
    - image:circleci/node:8

version: 2
jobs:
  prepare:
    <<: *defaults
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v2-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
        toot: .
        paths:
          - node_modules

  build:
    <<: *defaults
    steps:
      - checkout
      - attact_workspace:
        at: .
      - run: yarn build
      -persist_to_workspace:
        root: .
        paths: -dist

  test:
    <<: *defaults
    steps:
      - checkout
      - attact_workspace:
        at: .
      - run: yarn ci
      - store_test_results:
        path: test-results

workflows:
  version: 2
  build_accept_deploy:
    jobs:
      - prepare
      - build:
        requires:
          - test
      - test:
        requires:
          - prepare